Yoon_Online/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path("",index,name = "index"),
]

account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = "account"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("signup/", signup,name = "sign-up"),
    path("user/update/",user_update,name = "user_update"),
    path("user/delete/",user_delete,name = "user_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include("account.urls")),
    path('food/',include("food.urls")),
    path('store/',include("store.urls")),
    path('',include("Yoon_Online.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from .views import *

app_name = 'food'
urlpatterns = [
    path("order/create/",OrderCreate,name = "order_create"),
    path("order/list/",OrderList,name = "order_list"),
    path("order/detail/<int:id>",OrderDetail,name = "order_detail"),
    path("order/delete/<int:id>",OrderDelete,name = "order_delete"),

]

store/urls.py
from django.urls import path, include
from .views import *

app_name = "store"
urlpatterns = [
    path('table/',table_list,name = "table_list"),
]

Yoon_Online/models.py
from django.db import models

# Create your models here.

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser	# AbstractUser 불러오기
from phonenumber_field.modelfields import PhoneNumberField

class User(AbstractUser):
    phone_number = PhoneNumberField()

    def get_phone_num(self):
        value = str(self.phone_number)
        return value[:3] + '-' + value[3:7] + '-' + value[7:]

food/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name

class Menu(models.Model):
    name = models.CharField(max_length = 100, null = False)
    price = models.IntegerField(null = False)
    image = models.ImageField(upload_to = "menu")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

STATUS_CHOICES = (
    ('none', 'none'),
    ('in_progress','in_progress'),
    ('done','done')
)
class Order(models.Model):
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default = 'none')
    created_at = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey("account.User", on_delete=models.CASCADE)

    def total_price(self):
        sum = 0
        menu_orders = self.menu_order_set.all()
        for item in menu_orders:
            sum+= item.get_price()
        return sum

class Menu_Order(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField(null = False)

    def get_price(self):
        return self.menu.price * self.quantity

store/models.py
from django.db import models

class Table(models.Model):
    able = models.BooleanField(null = False)

Yoon_Online/views.py
from django.shortcuts import render
from food.models import Category

def index(request):
    context = {
        "categories" : Category.objects.all()
    }
    return render(request,"main.html",context)

account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib import messages
from .models import User


def signup(request):
    if request.method == 'POST':
        if User.objects.filter(username = request.POST.get("username")).exists():
            return render(request,"signup.html",{"message":"이미 존재하는 회원입니다."})
        else:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password'],
                first_name=request.POST['name'][0],
                last_name=request.POST['name'][1:],
                phone_number=request.POST.get("phonenum")
            )
            auth.login(request, user)
            return redirect('main:index')

    else:
        return render(request, 'signup.html')

def user_update(request):
    if request.method == "POST":
        user = request.user

        user.first_name = request.POST.get("name")[0]
        user.last_name = request.POST.get("name")[2:]
        if request.POST.get("password"):
            user.set_password(request.POST.get("password"))
        user.phone_number = request.POST.get("phone_number")
        user.save()
        auth.login(request,user)
        return redirect("main:index")
    else:
        return render(request,"editInfo.html")

def user_delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth.logout(request)
    return redirect("main:index")

food/views.py
from django.shortcuts import render, redirect
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Order, Menu, Menu_Order

@csrf_exempt
def OrderCreate(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            data = json.loads(request.body)
            order = Order(user = request.user)
            order.save()

            for item in data:
                menu = Menu.objects.get(name = item['name'])
                new = Menu_Order(menu = menu, order = order, quantity = item['quantity'])
                new.save()

            return JsonResponse({'success' : True,"id" : order.id},status = 200)
        else:
            return JsonResponse({'success':False,"error" : "로그인 후 이용해주세요."}, status=400)

    # POST 요청이 아니거나 AJAX 요청이 아닌 경우
    return JsonResponse({}, status=404)

def OrderList(request):
    order_list = Order.objects.filter(user = request.user)
    return render(request,"cart.html",{"order_list":order_list})

def OrderDetail(request,id):
    order = Order.objects.get(id = id)
    return render(request,"cartDetail.html",{"order":order})

def OrderDelete(request,id):
    order = Order.objects.get(id = id)
    order.delete()
    return redirect('food:order_list')

store/views.py
from django.shortcuts import render
from .models import Table
# Create your views here.
def table_list(request):
    tables = Table.objects.all()
    return render(request,"table.html",{"table_list":tables})

templates/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>장바구니</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
</head>
<body>
  <div class="cartWrap">
    {% include 'header.html' %}
    <div class="cartTitle">
      <h2>주문 내역</h2>
    </div>
      {% for order in order_list %}
        <div class="cartList">
            <div class="cartTapTop">
                <div class="cartTapTopLeft">
                    <div class="cartButton">
                        <img src="{% static 'img/cart.png'' %}" />
                        <p>식사 주문</p>
                    </div>
                    <div class="cartTime">
                        {{order.created_at|date:'Y-m-d H:i'}}
                    </div>
                </div>
                {% if order.status == "none" %}
                    <a href = "{% url 'food:order_delete' order.id %}" id="cartCheckLink">
                        <p class="cartTapTopRight">
                            주문취소
                        </p>
                    </a>

                {% else %}
                    <p class="cartTapTopRight">

                    </p>
                {% endif %}
            </div>
            <div class="cartTapBottom">
                <div class="cartMenuImg">
                    <img src="{% static 'img/yoon.jpeg'' %}" />
                </div>
                <div class="cartMenuInfo">
                    <p class="cartMenuName">윤가네</p>
                    <p class="cartMenuIntro">상명대 대표 맛집</p>
                    <div>
                        <button onclick="location.href='{% url 'main:index' %}'">재주문</button>
                        <button onclick="location.href='{% url 'food:order_detail' order.id %}'">주문상세</button>
                    </div>
                </div>
            </div>
        </div>
      {% endfor %}
  </div>
</body>
</html>

templates/cartDetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>주문내역 확인하기</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
</head>
<body>
  <div class="cartDetailWrap">
    {% include 'header.html' %}
    <div class="cartDetailTapWrap">
        <div class="cartDetailTop">
            {% if order.status == "none" %}
                <h3>주문확인중..</h3>
            {% elif order.status == "in_progress" %}
                <h3>조리중..</h3>
            {% else %}
                <h3>조리완료</h3>
            {% endif %}
          <div class="cartButton">
              <img src="{% static 'img/cart.png'' %}" />
              <p>식사주문</p>
          </div>
        </div>
        <div class="cartDivision"></div>
        <div class="cartDetailInfo">
            <div>
                <p>주문번호</p>
                <p>{{order.id}}</p>
            </div>
            <div>
                <p>주문시간</p>
                <p>{{order.created_at|date:'Y-m-d H:i'}}</p>
            </div>
        </div>
        <div class="cartDivision"></div>
        <div class="cartDetailMenuInfo">
            <h3>주문내역</h3>
            {% for item in order.menu_order_set.all %}
                <div>
                    <p>- {{item.menu.name}} x {{item.quantity}}</p>
                    <p>{{item.get_price}}원</p>
                </div>
            {% endfor %}

        </div>
        <div class="cartDivision"></div>
        <div class="cartTotalPrice">
            <h3>총 상품금액</h3>
            <h3>{{order.total_price}}원</h3>
        </div>
        <div class="cartDivision"></div>
        <div class="cartUserInfo">
            <h3>주문자 정보</h3>
            <div>
                <p>이름</p>
                <p>{{order.user.get_full_name}}</p>
            </div>
            <div>
                <p>연락처</p>
                <p>{{order.user.get_phone_num}}</p>
            </div>
        </div>
    </div>
  </div>
</body>
</html>

templates/editInfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>회원정보수정</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
<body>
    <div class="editInfoWrap">
        {% include 'header.html' %}
        <div class="editInfo">
            <h3>내 정보 수정</h3>
            <form action = "{% url 'account:user_update' %}" method = "post">
                {% csrf_token %}
                <div class="editInfoBox">
                    <div>
                        <p>이름</p>
                        <input type="text" name = "name" value="{{user.get_full_name}}"/>
                    </div>
                    <div>
                        <p>아이디</p>
                        <input type="text" name = "username" value = "{{user.username}}" disabled/>
                    </div>
                    <div>
                        <p>비밀번호</p>
                        <input type="password" name = "password" placeholder="새 비밀번호"/>
                    </div>
                    <div>
                        <p>번호</p>
                        <input type="text" name = "phone_number" value = "{{user.phone_number}}"/>
                    </div>
                </div>
                <input type = "submit" id = "editSB" style = "display:none">
            </form>
            <div class="signupBtWrap">
                <button id= "editBT" class="loginBt">정보 수정</button>
                <button class="loginBt" onclick = "location.href = '{% url 'account:user_delete' %}'">회원 탈퇴</button>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type = "text/javascript">
        $("#editBT").click(function(){
            $("#editSB").trigger("click")
        })
    </script>
</body>
</html>

templates/header.html
<div class="mainNav">
    <h2 onclick="location.href='{% url 'main:index' %}'">Yoon's online</h2>
    <div>
        {% if user.is_authenticated %}
            환영합니다 <a href = "{% url 'account:user_update' %}">{{request.user.get_full_name}}</a>님
            <button onclick="location.href='{% url 'food:order_list' %}'">주문내역</button>
            <button onclick="location.href='{% url 'account:logout' %}'">로그아웃</button>

        {% else %}
            <button onclick="location.href='{% url 'account:login' %}'">로그인</button>
            <button onclick="location.href='{% url 'account:sign-up' %}'">회원가입</button>
        {% endif %}
    </div>
</div>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>로그인</title>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <link rel="stylesheet" href="{% static '/css/index.css' %}">
</head>
<body>
<div class="loginWrap">
    {% include 'header.html' %}
    <div class="loginBody">
        <h2>- 로그인 -</h2>
        <form action = "{% url 'account:login' %}" method = "post">
            {% csrf_token %}
            <div class="loginInputWrap">
                <div>
                    <p>아이디</p>
                    <input type="text" name = "username"/>
                </div>
                <div>
                    <p>비밀번호</p>
                    <input type="password" name = "password"/>
                </div>
            </div>
            <div class="signupBtWrap">
                <button class="loginBt" >로그인</button>
                <input id = "loginSubmit" type = "submit" style = "display : none;">
            </div>
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script type = "text/javascript">
    $(".loginBt").click(function(){
        $("#loginSubmit).trigger("click");
    }
</script>
</body>
</html>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Yoon's online(윤가네 온라인)</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    {% include 'message.html' %}
    <div class="mainWrap">
        {% include 'header.html' %}
        <div class="mainTop">
            <button onclick="location.href='{% url 'store:table_list' %}'">자리 현황</button>
        </div>
        <div class="mainBottom">
            <h2>윤가네 주문하기</h2>
            <div class="mainBodyWrap">
                <div class="mainLeft">
                    {% for category in categories %}
                    <div class="menuKind">{{category.name}}</div>
                            <div class="menuTabWrap">
                                {% for menu in category.menu_set.all %}
                                    <div class="menuTap">
                                        <div class="menuName">
                                            <p class = "menu_name">{{menu.name}}</p>
                                            <p class = "menu_price">{{menu.price}}원</p>
                                        </div>
                                        <div class="menuImg">
                                            <img src="{{menu.image.url}}" />
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>

                    {% endfor %}

                </div>
                <div class="mainRight">
                    <div class="mainRightTitle">주문표</div>
                    <div id = "mainRightContent">
                    </div>

                    <div class="orderBtWrap">
                        주문하기
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <script>
    {% if message %}
        alert("{{ message }}");
    {% endif %}
  </script>
</body>
</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>로그인</title>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    {% include 'message.html' %}
    <div class="loginWrap">
        {% include 'header.html' %}
        <div class="loginBody">
            <h2>- 회원가입 -</h2>
            <form action = "{% url 'account:sign-up' %}" method = "post">
                {% csrf_token %}
                <div class="loginInputWrap">
                    <div>
                        <p>이름</p>
                        <input type="text" name = "name"/>
                    </div>
                    <div>
                        <p>아이디</p>
                        <input type="text" name = "username"/>
                    </div>
                    <div>
                        <p>비밀번호</p>
                        <input type="password" name = "password"/>
                    </div>
                    <div>
                        <p>번호</p>
                        <input type="text " name = "phonenum"/>
                    </div>
                </div>
                <input id = "signupSB" type = "submit"  style = "display:none">
            </form>
                <div class="signupBtWrap">
                    <button class="signupBt">회원가입</button>
                    <button class="loginBt" onclick="location.href='{% url 'account:login' %}'">로그인 하러 가기</button>

                </div>


        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script type = "text/javascript">
    $(".signupBt").click(function(){
        $("#signupSB").trigger("click");
    });
</script>
</body>
</html>

templates/table.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>자리 현황</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    <div class="tableWrap">
        {% include 'header.html' %}
        <div class="tableBodyWrap">
            <h2>- 자리 현황 -</h2>
            <div class="tableDis">
                {% for table in table_list %}
                    {% if table.able %}
                        <div style = "background-color: green;">{{table.id}}</div>
                    {% else %}
                        <div style = "background-color: red;">{{table.id}}</div>
                    {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
</body>
</html>